- title: Kubernetes
  fulltitle: kubernetes dev 
  description: kubernetes Documentation
  tag: kubernetes
  icon: /images/thingsboard-c-icon.svg
  path: /docs/kubernetes/
  guides: /docs/kubernetes/guides/
  docsPrefix: /docs/kubernetes/
